# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='label',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
